# Site settings
title: Dream People
description: Dream People Band
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dream People
user_description: "Os Dream People são Francisco, Bernardo, Nuno, Chris e Bóris. Antes de 2018 nenhum se
conhecia. Os Dream People são por isso um verdadeiro mosaico de personalidades,
traços, manias e gostos distintos, o que se reflete na música que fazem, também ela um
exercício de constante busca identitária, reinvenção e expansão criativa. Se numa música
nos conduzem ao etéreo universo do dream pop, noutra envolvem-nos num psicadelismo
desértico reminescente a uns modernos Doors. Assim são os Dream People, uma família
única e multidimensional."
user_title: ""
email: dreampeopleband@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
